ALTER TABLE meeting_rsvps
  ADD COLUMN IF NOT EXISTS attended_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS attendance_marked_by BIGINT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE meeting_guests
  ADD COLUMN IF NOT EXISTS attended_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS attendance_marked_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
